### ISSUE TITLE
100% static JavaScript

### ISSUE THREAD

**Issue by MichiK** [c3bottles/c3bottles#106]
Instead of templating JS code (even if it's only a few lines) we should add the dynamic stuff to the template of the page itself somewhere and parse it from static JS. Often, the information in the HTML source and the JS are nearly the same anyway, so that could reduce server load significantly in high load scenarios and saves one HTTP query per page impression as well.

This probably needs some thinking about the drop point status badges.

**Comment by spruce** [comment]
I haven’t looked through all of the code and how everything works together. But I would try and create a Frontend-only version. I think it would make it even simpler deployment-wise. Would you be interested in such an endeavor?
