### ISSUE TITLE
Implement rate limiting

### ISSUE THREAD

**Issue by MichiK** [c3bottles/c3bottles#42]

**Comment by jelly** [comment]
Something to think about is implementing detecting "trolls", which on SHA 2017 reported all drop points as full while they weren't. Implementing that might however not be very trivial or work well, since the reports might be valid.

**Comment by der-michik** [comment]
[Flask-Limiter](https://flask-limiter.readthedocs.io/en/stable/) could be the way to go...

**Comment by pintman** [comment]
Although this would be a great feature, how do you decide if the current report is correct or fraudulent? I think that the system is more or less build on trust and can easily be trolled - even if with a rate limit applied.

**Comment by MichiK** [comment]
Considering that this is open since nearly 5 years now, nobody came up with a really cool idea and the ecosystem has eveolved since then, I think it would be better to leave this to the operators. DDoS protection etc. could e.g. be covered by a reverse proxy in the Docker stack by blocking a lot of consecutive calls to certain URLs from the same IP adress etc.
