### ISSUE TITLE
Coordinates on the map are geographical and in no linear relationship with pixel distances

### ISSUE THREAD

**Issue by der-michik** [c3bottles/c3bottles#44]
This makes collaboration with tools like c3nav frustratingly difficult. Since the CCH is essentially planar there should be an easy relationship between coordinates and pixels on the map so that the transformation of the coordinates into another map coordinate system is a simple linear transformation.

**Comment by der-michik** [comment]
See http://leafletjs.com/examples/crs-simple/crs-simple.html

**Comment by sebastius** [comment]
For outdoor-events GPS coordinates combined with OpenStreetMap or something would be awesome.

**Comment by der-michik** [comment]
That should be really easy actually as we just would have to add an OSM layer (one line in the Leafjet JS stuff) and change the default zoom to the event location.

**Comment by der-michik** [comment]
This will be redundant as soon as we add some c3nav connection and if not, that doesn't matter and does not apply to OSM layers right now as well.
