### ISSUE TITLE
Add all the l10n stuff

### ISSUE THREAD

**Issue by der-michik** [c3bottles/c3bottles#62]
* [x] l10n infrastructure & scripts
* [x] l10n code
* [x] translate all the templates:
  * [x] create_dp.html
  * [x] dp_js.html
  * [x] dp_modals.html
  * [x] dp_modals_list.html
  * [x] dp_modals_map.html
  * [x] edit_dp.html
  * [x] error.html
  * [x] faq.html
  * [x] footer.html
  * [x] index.html
  * [x] layout.html
  * [x] list.html
  * [x] macros/actions.html
  * [x] macros/states.html
  * [x] map.html
  * [x] navbar.html
  * [x] report_buttons.html
  * [x] report.html
  * [x] statistics.html
  * [x] success.html
  * [x] view.html
  * [x] visit_buttons.html
  * [x] visit.html
* [x] translate strings from the model
* [x] add dynamic JS with the strings
* [x] translate all the JS strings
* [x] allow the user to switch the language (and disable the language switcher is there is only one)

**Comment by sebastius** [comment]
Can i also use the language-switcher to change texts based on the event? I plan to use C3bottles for waste-removal (not bottles) and i'd like to do my own texts for SHA2017.

**Comment by der-michik** [comment]
My idea was that you simply have one or several languages that correspond to natural languages and are not event-dependent per se. To adapt the system to an event, you then could just change the .po file(s) to reflect the texts you need. So we would have both: some localization and event-dependent texts.

Of course, if there is only one language available, all the language switching stuff in the frontend is not visible as there is only one language to use anyway.

**Comment by sebastius** [comment]
Ah like that. When do you expect to have the l10n 'stuff' complete? I'd like to begin making a final translation for SHA2017 :)

**Comment by der-michik** [comment]
There are a few strings still hard-coded in the Javascript. There are different approaches on how to translate them properly and integrate that with the translation of the Python parts. I still have to think about that a bit.

Concerning the changes needed for SHA2017 I guess I will first change the building level and room code from hard-coded in the JS to dynamically stored in the database and being editable by admins on the map (or at least being able to disable that alltogether).
