### ISSUE TITLE
List does not show anything

### ISSUE THREAD

**Issue by BerndKeller** [c3bottles/c3bottles#86]
the drop points are on the map but not listed. noot noot

**Comment by der-michik** [comment]
Alles kaputt. Such mal den marudor, der hats kaputtgemacht. Ich hab grad keine Hirnkapazität dafür, das heile zu frickeln.

**Comment by marudor** [comment]
Fixed with 5c27e24abe3ffa7603bfdd41beb8e05cf8564192
